receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: prateek_crud_app
  otlp:
    endpoint: "tempo:4317" # ✅ Export to Tempo using OTLP
    tls:
      insecure: true # ✅ Required if Tempo does not use TLS

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp] # ✅ Send traces to Tempo using OTLP
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]
