receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  hostmetrics: # New host metrics receiver
    collection_interval: 60s
    scrapers:
      cpu:
      memory:
      disk:
      network:

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: prateek_crud_app
  otlp:
    endpoint: 'tempo:4317'
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp]
    metrics:
      receivers: [otlp, hostmetrics] # Add hostmetrics to the metrics pipeline
      processors: [batch]
      exporters: [debug, prometheus]
